# Generated by Django 3.2.23 on 2024-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_orderitem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='name',
        ),
    ]
